# Generated by Django 5.2.1 on 2025-06-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('room_des', models.TextField()),
                ('room_price', models.IntegerField()),
                ('room_facilities', models.CharField(max_length=255)),
                ('room_image', models.ImageField(upload_to='rooms/')),
            ],
        ),
    ]
