# Generated by Django 5.2.1 on 2025-06-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_facilities',
            field=models.TextField(),
        ),
    ]
