# Generated by Django 5.2.1 on 2025-06-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0002_alter_rooms_room_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_number',
            field=models.IntegerField(default='0'),
        ),
    ]
