# Generated by Django 5.2.1 on 2025-06-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0003_rooms_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='room_number',
        ),
    ]
