# Generated by Django 5.2.1 on 2025-06-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0004_remove_rooms_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_facilities',
            field=models.TextField(default='WiFi,TV,AC'),
        ),
    ]
