# Generated by Django 5.2.1 on 2025-06-24 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0008_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motel.rooms')),
            ],
        ),
        migrations.DeleteModel(
            name='Checkin',
        ),
        migrations.AddField(
            model_name='contactus',
            name='address1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactus',
            name='address2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactus',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactus',
            name='firstName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactus',
            name='lastName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='postal',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='roomname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='motel.rooms'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
    ]
