# Generated by Django 5.2.1 on 2025-06-24 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0009_room_delete_checkin_contactus_address1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='postal',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='roomname',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='state',
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal', models.IntegerField()),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('roomname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motel.rooms')),
            ],
        ),
    ]
