# Generated by Django 5.2.1 on 2025-06-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0010_remove_contactus_address1_remove_contactus_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='phone',
            field=models.IntegerField(default='0'),
        ),
    ]
