# Generated by Django 5.2.1 on 2025-07-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0013_useraccount_date_joined_useraccount_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_staff',
        ),
    ]
