# Generated by Django 6.0.2 on 2026-03-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0015_bookings_check_in_bookings_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='number_of_rooms',
            field=models.IntegerField(default=1, help_text='Number of rooms available in this category'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
