# Generated by Django 6.0.2 on 2026-03-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel', '0016_rooms_number_of_rooms_alter_rooms_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
